server {
	listen 8000 default_server;
	listen [::]:8000 default_server;

	root /var/www/html/client;

	location / {
		index index.html;
	}

	location /assets/ {
		try_files $uri $uri/;
	}

	location /api/v1/ {
		rewrite ^/api/v1(.*)$ $1 break;
		proxy_pass http://localhost:8001;
	}
}

server {
	listen 8001 default_server;
	listen [::]:8001 default_server;

	root /var/www/html/api/src;

	location / {
		index index.php;
		try_files $uri $uri/ @handler;
	}

	location @handler {
		rewrite ^/(.*)$ /index.php last;
	}

	location ~ .php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php-fpm.sock;
		fastcgi_index index.php;
		include fastcgi.conf;
	}

	# You may need this to prevent return 404 recursion.
	location = /404.html {
		internal;
	}
}

# vim: filetype=nginx
